// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:f621b345-ce29-4770-99fd-3320532fec71",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_uW9CObb3H",
    "aws_user_pools_web_client_id": "64dfq38n817ktjd2dkhmbmhh4c",
    "oauth": {}
};


export default awsmobile;
